accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/',views.logout,name="logout"),

    path('user_page/<int:id>/', views.user_page, name='user_page'),
    path('edit_profile/<int:id>/', views.edit_profile, name='edit_profile'),

    path('follow/<int:id>/', views.follow, name='follow'),

]

insta/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/',include('posts.urls')),
    path('accounts/',include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill

class User(AbstractUser):
    follow = models.ManyToManyField(settings.AUTH_USER_MODEL,related_name='follower', blank=True)
    # follow = models.ManyToManyField("self", blank=True)
    profile_image = ProcessedImageField(
                upload_to='posts/images',                # 저장 위치
                processors=[ResizeToFill(150, 150)],     # 처리할 작업 목록
                format='JPEG',                           # 저장 포맷
                options={'quality':90},                  # 옵션
                blank=True
    )
    def __str__(self):
        return self.username






# 예전코드 

# # 국제화를 위한 코드 안써도 됨. 사용한 이유는 장고의 기본 user 내부에서도 똑같이 사용되었기 때문
# # 국제화? 'email address'가 한국어 설정에서는 '이메일'로 변경
# from django.utils.translation import ugettext_lazy as _

# from .managers import CustomUserManager

# class User(AbstractUser):
#     # # 기존의 user 모델은 username이라는 칼럼을 이용해서 로그인을 했음
#     # # email을 이용해서 로그인을 하기 위하여 다음과 같이 코드 작성
#     # # 기존에 있던 user모델도 email 칼럼이 있지만 unique=True 옵션을 주기 위해서 새로 작성
#     # email = models.EmailField(_('email address'), unique=True)

#     # # USERNAME_FIELD 를 아이디 값으로 사용한다.
#     # USERNAME_FIELD = 'email'
#     # REQUIRED_FIELDS = ['username',]
    
#     # # 생성을 관리해주는 Manager를 objects로 등록해야함.
#     # # managers.py 를 만들어서 따로 작성
#     # objects = CustomUserManager()

#     # def __str__(self):
#     #     return self.email

posts/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.conf import settings

# Create your models here.
class Hashtag(models.Model):
    # 같은 이름의 해시태그는 하나만 존재해야 하기때문에 unique=True
    content = models.TextField(unique=True)

    def __str__(self):
        return self.content

class Post(models.Model):
    content = models.CharField(max_length=100)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # related_name 을 설정해주는 이유 - 역참조에서 문제발생
    # user 칼럼도 settings.AUTH_USER_MODEL과 관계 설정이 되어있다. 
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_post_set',blank=True)
    hashtag = models.ManyToManyField(Hashtag, blank=True)

class Image(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    file = ProcessedImageField(
                upload_to='posts/images',                # 저장 위치
                processors=[ResizeToFill(600, 600)],     # 처리할 작업 목록
                format='JPEG',                           # 저장 포맷
                options={'quality':90},                  # 옵션
    )

class Comment(models.Model):
    content = models.CharField(max_length=100)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm

from .models import User


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = User
        fields = ('username','email',)

class CustomUserAuthenticationForm(AuthenticationForm):
    
    class Meta:
        model = User
        # fields = ('email',)

class CustomUserChangeForm(UserChangeForm):
    
    password = None

    class Meta:
        model = User
        fields = ('email','profile_image',)

accounts/views.py
from django.shortcuts import render, redirect
# from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from .models import User
from .forms import CustomUserAuthenticationForm, CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def signup(request):
    if request.method=="POST":
        # 사용자를 등록하는 로직
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('posts:list')
        
    else: 
        # 정보를 입력하는 폼을 전달
        form = CustomUserCreationForm()
    return render(request,'accounts/signup.html',{'form':form})


def login(request):
    # 이미 로그인 했으면서 또 로그인 페이지 보여달라고 할때
    if request.user.is_authenticated:
        return redirect('posts:list')
        
    #사용자가 로그인을 요청했으면?
    if request.method == "POST": 
        form =  CustomUserAuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('posts:list')
    
    #로그인을 위한 폼을 요청했을때?
    else:
        form = CustomUserAuthenticationForm()
    return render(request,'accounts/login.html',{'form':form})

def logout(request):
    auth_logout(request)
    return redirect('posts:list')

def user_page(request,id):
    user_info = User.objects.get(id=id)
    return render(request, 'accounts/user_page.html',{'user_info':user_info})

@login_required
def follow(request,id):
    me = request.user
    you = User.objects.get(id=id)
    if me != you:
        # 사용자가 이미 팔로우를 눌렀으면 취소
        if me.follow.filter(id=you.id).exists():
            me.follow.remove(you)
        # 안눌렀으면 좋아요
        else:
            me.follow.add(you)
    return redirect('accounts:user_page',id)

@login_required
def edit_profile(request,id):
    me = request.user
    you = User.objects.get(id=id)
    if me == you:
        if request.method == "POST":
            form = CustomUserChangeForm(request.POST, request.FILES, instance=me)
            if form.is_valid():
                form.save()
                return redirect('accounts:user_page', id)
        else:
            form = CustomUserChangeForm(instance=me)
            
        return render(request, 'accounts/edit_profile.html', {'form':form})

    return redirect('accounts:user_page',id)

accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
    <form action="" method="post" enctype="multipart/form-data" accept="image/*">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">Submit</button>
        {% endbuttons %}
    </form>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
    <form action="" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">Submit</button>
        {% endbuttons %}
    </form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
    <form action="" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">Submit</button>
        {% endbuttons %}
    </form>
{% endblock %}

accounts/templates/accounts/user_page.html
{% extends 'base.html' %}
{% block body %}
<div class='row my-5 mx-auto'>
    <div class="col-4 d-flex justify-content-center">
        <!-- 프로필이미지가 들어올공간 -->
        <!-- 이미지 없으면 기본이미지 사용 -->
        {% if user_info.profile_image %}
            <img src="{{user_info.profile_image.url}}" alt="" class="rounded-circle">
        {% else %}
            <img src="/media/posts/images/ab.jpg" alt="" class="rounded-circle">
        {% endif %}
    </div>
    <div class="col-5">
        <div class="row ">
            <h2>{{user_info.username}}</h2>
            <!-- 팔로우 버튼, 게시물수, 팔로우 수, 자기소개 등이 들어올 공간 -->
            {% if user != user_info %}
                {% if user_info in user.follow.all %}
                    <a href="{% url 'accounts:follow' user_info.id %}" class="btn btn-light mx-3">팔로잉</a>
                {% else %}
                    <a href="{% url 'accounts:follow' user_info.id %}" class="btn btn-primary mx-3">팔로우</a>
                {% endif %}
            {% else %}
                <a href="{% url 'accounts:edit_profile' user.id %}" class="btn btn-light mx-3">프로필 편집</a>
            {% endif %}
        </div>
        <div class="row d-flex justify-content-between">
            <h4>게시물 {{user_info.post_set.count}}</h4>
            <h4>팔로워 {{user_info.follower.count}}</h4>
            <h4>팔로우 {{user_info.follow.count}}</h4>
        </div>
        <div class="row">
            <h4>자기소개</h4>
        </div>
    </div>
</div>
<div class="card-columns">
    {% for post in user_info.post_set.all %}
        {% include 'posts/_post.html' %}
    {% endfor %}
</div>
{% endblock %}