accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/',views.logout,name="logout"),

    path('user_page/<int:id>/', views.user_page, name='user_page'),
    path('edit_profile/<int:id>/', views.edit_profile, name='edit_profile'),

    path('follow/<int:id>/', views.follow, name='follow'),

]

insta/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts/',include('posts.urls')),
    path('accounts/',include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views
app_name = 'posts'

urlpatterns = [
    path('create/', views.create, name="create"),
    path('', views.list, name='list'),
    path('<int:id>/update/', views.update, name='update'),

    path('<int:id>/comment/create/', views.comment_create, name='comment_create'),

    path('<int:id>/like/', views.like, name="like"),

    path('hashtag/<int:id>/', views.hashtag, name='hashtag'),

]

posts/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.conf import settings

# Create your models here.
class Hashtag(models.Model):
    # 같은 이름의 해시태그는 하나만 존재해야 하기때문에 unique=True
    content = models.TextField(unique=True)

    def __str__(self):
        return self.content

class Post(models.Model):
    content = models.CharField(max_length=100)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # related_name 을 설정해주는 이유 - 역참조에서 문제발생
    # user 칼럼도 settings.AUTH_USER_MODEL과 관계 설정이 되어있다. 
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_post_set',blank=True)
    hashtag = models.ManyToManyField(Hashtag, blank=True)

class Image(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    file = ProcessedImageField(
                upload_to='posts/images',                # 저장 위치
                processors=[ResizeToFill(600, 600)],     # 처리할 작업 목록
                format='JPEG',                           # 저장 포맷
                options={'quality':90},                  # 옵션
    )

class Comment(models.Model):
    content = models.CharField(max_length=100)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    

posts/forms.py
from django import forms
from .models import Post, Image, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['content',]

class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['file',]
        widgets = {
            'file': forms.FileInput(attrs={'multiple': True}),
        } 

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content',]

posts/views.py
from django.shortcuts import render, redirect
from .forms import PostForm, ImageForm, CommentForm
from .models import Post, Image, Hashtag
from django.db import transaction
from django.contrib.auth.decorators import login_required

# Create your views here.
def list(request):
    posts = Post.objects.order_by('-id').all()
    comment_form = CommentForm()
    return render(request,'posts/list.html',{'posts':posts, 'comment_form':comment_form})

@login_required
def create(request):
    # 1. get 방식으로 데이터를 입력할 form 을 요청한다.
    # 4. 사용자가 데이터를 입력하여 post 요청을 보낸다.
    # 9. 사용자가 다시 적절한 데어터를 입력하여 post 요청을 보낸다.
    if request.method == 'POST':
        # 5. post방식으로 저장요청을 받고 데이터를 받아 PostForm에 넣어 인스턴스화 한다.
        # 10. 5번과 같음
        post_form = PostForm(request.POST)
        image_form = ImageForm(request.FILES)
        # 6. 데이터 검증을 한다.
        # 11. 6번과 같음
        if post_form.is_valid():
            # 12. 적절한 데이터가 들어온다. 데이터를 저장하고 list 페이지로 리다이렉트 시킨다.
            post = post_form.save(commit=False)
            post.user = request.user
            post.save()
            
            # 해쉬태그 기능 추가
            # is_valid() 함수를 통과한 cleaned_data에서 content를 가져온다.
            content = post_form.cleaned_data.get('content')
            # 내용을 split()함수로 띄어쓰기를 기준으로 잘라서 단어로 만든다
            content_word = content.split()
            for word in content_word:
                # 단어의 첫글자가 #으로 시작하면
                if word[0] == '#':
                    # get_or_create로 해쉬태를 찾고 없으면 생성한다.
                    tag = Hashtag.objects.get_or_create(content=word)
                    # 찾거나 생성한 해쉬태그를 post에 M:N관계로 추가한다.
                    # tag[0]으로 추가하는 이유 : get_or_create의 리턴은 (hashtag객체, True or False) 형태의 튜플이기때문
                    post.hashtag.add(tag[0])
            
            for image in request.FILES.getlist('file'):
                request.FILES['file'] = image
                image_form = ImageForm(request.POST,request.FILES)
                if image_form.is_valid():
                    image = image_form.save(commit=False)
                    image.post = post
                    image.save()
            return redirect('posts:list')  
        else:
            # 7. 적절하지 않은 데이터가 들어온다.
            # 아무내용이 없기 때문에 else문은 생략
            pass
        
    else:
        # 2. PostForm을 인스턴스화 해서 form에 저장한다. 
        post_form = PostForm()
        image_form = ImageForm()
    # 3. form을 담아서 create.html을 보내준다.
    # 8. 사용자가 입력한 데이터는 form에 담아진 상태로 다시 form을 담아서 create.html을 보내준다.
    return render(request,'posts/form.html', {'post_form':post_form, 'image_form':image_form})

@login_required
def update(request,id):
    post = Post.objects.get(id=id)
    if post.user == request.user:
        if request.method == 'POST':
            post_form = PostForm(request.POST, instance=post)
            if post_form.is_valid():
                post_form.save()

                # 기존의 해쉬태그를 전부 삭제
                post.hashtag.clear()
                # 아래는 해쉬태그를 추가하는 로직과 동일
                content = post_form.cleaned_data.get('content')
                content_word = content.split()
                for word in content_word:
                    if word[0] == '#':
                        tag = Hashtag.objects.get_or_create(content=word)
                        post.hashtag.add(tag[0])
                return redirect('posts:list')  
            else:
                pass
        else:
            post_form = PostForm(instance=post)
    else:
        return redirect('posts:list')
    return render(request,'posts/form.html', {'post_form':post_form})

@login_required
def comment_create(request,id):
    post = Post.objects.get(id=id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.post = post
            comment.save()
            return redirect('posts:list')

@login_required
def like(request,id):
    user = request.user
    post = Post.objects.get(id=id)
    
    # 사용자가 like를 눌렀으면 취소
    if post.likes.filter(id=user.id).exists():
        post.likes.remove(user)
    # 안눌렀으면 좋아요
    else:
        post.likes.add(user)
    # data = {'likes_count' : post.like.count()}
    return redirect('posts:list')

def hashtag(request,id):
    hashtag = Hashtag.objects.get(id=id)
    posts = hashtag.post_set.all()
    # list 페이지를 재활용하기 위해서 CommentForm도 추가하여 list와 동일하게 구성
    comment_form = CommentForm()
    # 페이지에서 어떤 해쉬태그를 클릭했는지 표시하기 위해서 hashtag 도 같이 리턴
    return render(request, "posts/list.html", {"posts":posts,"comment_form":comment_form, "hashtag":hashtag})

posts/templates/posts/_post.html
{% load posts_templatetag %}
<div class="card my-5">
    <div class="card-header">
        <!-- 게시물 작성자 클릭시 해당유저 페이지로 이동 -->
        <a href="{% url 'accounts:user_page' post.user.id %}" style="color:black">{{post.user}}</a>
    </div>
    {% if post.image_set %}
    <div id="post{{post.id}}" class="carousel slide carousel-fade" data-ride="carousel">

        <div class="carousel-inner">
            {% for image in post.image_set.all %}
                <div class="carousel-item {% if forloop.counter == 1 %} active {% endif %}">
                    <img src="{{ image.file.url }}" class="d-block w-100" alt="...">
                </div>
            {% endfor %}
            <a class="carousel-control-prev" href="#post{{post.id}}" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#post{{post.id}}" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
    {% else %}
        <img src="..." alt="..." class="card-img-top" />
    {% endif %}
    <div class="card-body">
        <!-- 좋아요 버튼 시작 -->
        {%if user in post.likes.all %}
            <a href="{% url 'posts:like' post.id %}" id="like" name="{{post.id}}"> <i id="heart" class="fas fa-heart fa-lg" style="color:#ed4956"> </i> </a>
        {%else%}
            <a href="{% url 'posts:like' post.id %}" id="like" name="{{post.id}}"> <i id="heart" class="far fa-heart fa-lg" style="color:black"><span id="like_count" class="badge badge-light"></span></i> </a>
        {%endif%}
        <!-- 기존코드 -->
        <p class="card-text"><strong>{{post.user}}</strong> {{post.content}}</p>
        <!-- 커스텀템플릿필터 적용 -->
        <p class="card-text"><strong>{{post.user}}</strong> {{post|hashtag_link|safe}}</p>        
        <p class="card-text">좋아요 {{post.likes.count}}개</p>
        <!-- 좋아요 끝 -->
        {% if user == post.user %}
            <a href="{% url 'posts:update' post.id %}" class="btn btn-warning">수정</a>
        {% endif %}
    </div>
    <div class="card-body">
        {% for comment in post.comment_set.all %}
            <p class="card-text"><strong>{{comment.user}}</strong> {{comment.content}}</p>
        {% empty %}
            <p class="card-text">댓글이 없습니다.</p>
        {% endfor %}
    </div>
    <div class="card-footer">
        <form action="{% url 'posts:comment_create' post.id %}" method="post">
            {% csrf_token %}
            {{ comment_form.content }}
            <input type="submit" value="게시" class="btn-light">
        </form>
    </div>
</div>

posts/templates/posts/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
    <form action="" method="post" enctype="multipart/form-data" accept="image/*">
        {% csrf_token %}
        {% bootstrap_form post_form %}
        {% if image_form %}
            {% bootstrap_form image_form show_label=False %}
        {% endif %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">Submit</button>
        {% endbuttons %}
    </form>
{% endblock %}

posts/templates/posts/list.html
{% extends 'base.html' %}
{% block body %}
    {% if request.resolver_match.url_name == 'hashtag' %}
        <h2>{{hashtag.content}}</h2>
    {% endif %}
    <div class="row">
        <div class="col-6">
            {% for post in posts %}
                {% include 'posts/_post.html' %}
            {% endfor %}
        </div>
    </div>
{% endblock %}